### ISSUE TITLE
There was an error when compiling, and there was no error message

### ISSUE THREAD

**Issue by bigfacewo** [dynamind/minimal-vue-worker#7]
Hello, I used the web worker according to your tutorial. When I used the development mode, although the compilation error was wrong, the page could still be opened normally, but it was not in the production mode. He just prompted me to compile errors, but there was no specific error message. Have you ever encountered this problem and how to solve it? Thank you very much.
![image](https://user-images.githubusercontent.com/31603897/90947780-2153e000-e46b-11ea-9fee-0b572b9f0e28.png)

**Comment by dynamind** [comment]
No, I haven’t seen that before. Possibly an issue with newer packages/cli version? The example is already quite old, and I haven’t kept it up to date

**Comment by bigfacewo** [comment]
I changed to [this library](https://github.com/GoogleChromeLabs/worker-plugin) and solved my problem.
